language: python
python:
  - "2.7"

branches:
  only:
    - master
    - dev

install:
  - "pip install ."
  - "pip install -e .[testing]"  # for installing `tests_require`

script:
  - "python setup.py nosetests"
